export const platformList = [
    "PS5",
    "XBOX",
    "PC",
    "Nintendo Switch",
    "Nintendo WII",
    "PS4",
    "PS3",
    "PS2",
    "PSX",
    "Nintendo 64",
    "XBOX360",
    "Dreamcast",
    "Super Nintendo",
    "Nintendo",
    "Nintendo GC",
]